version: '3.8'
services:
  backend:
    image: bureclass-backend
    container_name: bureclass-backend
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    volumes:
      - ./backend:/app/backend
    command: "fastapi dev backend/main.py --host 0.0.0.0 --port 80"
    env_file:
      - .env
    networks:
      - bureclass-conn
    user: 1000:1000

  frontend:
    image: node:22.2.0-alpine3.19
    container_name: bureclass-frontend
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: "npm run dev -- --host 0.0.0.0"
    networks:
      - bureclass-conn
    user: 1000:1000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
          ignore:
            - node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:1.25.5
    container_name: bureclass-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - bureclass-conn
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}

  search:
    image: elasticsearch:8.7.1
    container_name: bureclass-search
    restart: unless-stopped
    environment:
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
        - "xpack.security.enabled=false"
        - "discovery.type=single-node"
        - "bootstrap.memory_lock=true"
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    volumes:
        - search-data:/usr/share/elasticsearch/data
    networks:
        - bureclass-conn

volumes:
  search-data:

networks:
  bureclass-conn:
    name: 'bureclass-conn'
    driver: bridge
