version: '3.8'
services:
  backend:
    image: bureclass-backend
    container_name: bureclass-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile-backend
    env_file:
      - .env
    command: "uvicorn backend.main:app --host 0.0.0.0 --port 80"
    networks:
      - bureclass-conn
    volumes:
      - backend-data:/app/data

  frontend:
    image: bureclass-frontend
    container_name: bureclass-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile-frontend
    networks:
      - bureclass-conn

  nginx:
    image: nginx:1.25.5
    container_name: bureclass-nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - bureclass-conn
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}

  search:
    image: elasticsearch:8.7.1
    container_name: bureclass-search
    restart: unless-stopped
    environment:
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
        - "xpack.security.enabled=false"
        - "discovery.type=single-node"
        - "bootstrap.memory_lock=true"
        - "ES_JAVA_OPTS=-Xms8192m -Xmx8192m"
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    volumes:
        - search-data:/usr/share/elasticsearch/data
    networks:
        - bureclass-conn

volumes:
  search-data:
  backend-data:

networks:
  bureclass-conn:
    name: 'bureclass-conn'
    driver: bridge
