FROM python:3.12.0-bookworm

WORKDIR /app

COPY backend/requirements.txt .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY ./backend/save_models.py .
RUN python save_models.py

COPY backend ./backend

CMD uvicorn backend.main:app --host 0.0.0.0 --port 80
